export interface CodeLine {
  id: number;
  code: string;
  hasBug: boolean;
  bugType?: string;
  correctCode?: string;
  hint?: string;
}

export interface BugHunter2Level {
  id: number;
  title: string;
  story: string;
  concept: string;
  difficulty: 'Easy' | 'Medium' | 'Hard' | 'Expert';
  lines: CodeLine[];
  expectedOutput: string;
  bugCount: number;
}

/** Bug Hunter 2 — 30 levels, easy → expert. Player must type every fix. */
export const bugHunter2Levels: BugHunter2Level[] = [
  // ——— EASY (1–8) ———
  {
    id: 1,
    title: 'Quote Quake',
    story: '🤖 The greeting string fell apart!',
    concept: 'Strings need matching quotes on both ends',
    difficulty: 'Easy',
    expectedOutput: 'Hi, coder!',
    bugCount: 1,
    lines: [
      {
        id: 1,
        code: 'let msg = "Hi, coder!;',
        hasBug: true,
        bugType: 'Missing closing quote',
        correctCode: 'let msg = "Hi, coder!";',
        hint: 'Close the string with " before the semicolon.',
      },
      { id: 2, code: 'console.log(msg);', hasBug: false },
    ],
  },
  {
    id: 2,
    title: 'Semicolon Slip',
    story: '🎮 Score line is incomplete!',
    concept: 'End statements with a semicolon',
    difficulty: 'Easy',
    expectedOutput: 'Score: 50',
    bugCount: 1,
    lines: [
      {
        id: 1,
        code: 'let score = 50',
        hasBug: true,
        bugType: 'Missing semicolon',
        correctCode: 'let score = 50;',
        hint: 'Add ; at the end of the statement.',
      },
      { id: 2, code: 'console.log("Score: " + score);', hasBug: false },
    ],
  },
  {
    id: 3,
    title: 'Case Chaos',
    story: '🐱 The name variable got its case mixed up!',
    concept: 'Variable names are case-sensitive',
    difficulty: 'Easy',
    expectedOutput: 'Pixel',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let petName = "Pixel";', hasBug: false },
      {
        id: 2,
        code: 'console.log(petname);',
        hasBug: true,
        bugType: 'Wrong casing',
        correctCode: 'console.log(petName);',
        hint: 'petName has a capital N.',
      },
    ],
  },
  {
    id: 4,
    title: 'Forgotten Let',
    story: '🎂 Candles appeared from nowhere!',
    concept: 'Declare variables with let (or const)',
    difficulty: 'Easy',
    expectedOutput: '12',
    bugCount: 1,
    lines: [
      {
        id: 1,
        code: 'candles = 12;',
        hasBug: true,
        bugType: 'Undeclared variable',
        correctCode: 'let candles = 12;',
        hint: 'Start with let before the name.',
      },
      { id: 2, code: 'console.log(candles);', hasBug: false },
    ],
  },
  {
    id: 5,
    title: 'Paren Panic',
    story: '📢 console.log is missing a piece!',
    concept: 'Function calls need matching parentheses',
    difficulty: 'Easy',
    expectedOutput: 'Ready!',
    bugCount: 1,
    lines: [
      {
        id: 1,
        code: 'console.log("Ready!";',
        hasBug: true,
        bugType: 'Missing closing parenthesis',
        correctCode: 'console.log("Ready!");',
        hint: 'Close the ( after the string.',
      },
    ],
  },
  {
    id: 6,
    title: 'Plus Not Comma',
    story: '🧩 Glue text and a number together!',
    concept: 'Use + to concatenate strings and numbers',
    difficulty: 'Easy',
    expectedOutput: 'Level 3',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let n = 3;', hasBug: false },
      {
        id: 2,
        code: 'console.log("Level " , n);',
        hasBug: true,
        bugType: 'Wrong join operator',
        correctCode: 'console.log("Level " + n);',
        hint: 'Replace the comma with +.',
      },
    ],
  },
  {
    id: 7,
    title: 'Quote Mismatch',
    story: '📝 Opening " but closing with something else!',
    concept: 'Opening and closing quotes must match',
    difficulty: 'Easy',
    expectedOutput: 'Go!',
    bugCount: 1,
    lines: [
      {
        id: 1,
        code: "let shout = \"Go!';",
        hasBug: true,
        bugType: 'Mismatched quotes',
        correctCode: 'let shout = "Go!";',
        hint: 'Use " on both sides (or both \').',
      },
      { id: 2, code: 'console.log(shout);', hasBug: false },
    ],
  },
  {
    id: 8,
    title: 'Const Trap',
    story: '🔒 You tried to change a const!',
    concept: 'Use let if the value will change',
    difficulty: 'Easy',
    expectedOutput: '2',
    bugCount: 1,
    lines: [
      {
        id: 1,
        code: 'const lives = 1;',
        hasBug: true,
        bugType: 'const cannot be reassigned',
        correctCode: 'let lives = 1;',
        hint: 'Change const to let so lives can update.',
      },
      { id: 2, code: 'lives = 2;', hasBug: false },
      { id: 3, code: 'console.log(lives);', hasBug: false },
    ],
  },
  // ——— MEDIUM (9–16) ———
  {
    id: 9,
    title: 'Zero Start',
    story: '🍎 Grab the first fruit — arrays start at 0!',
    concept: 'First array index is 0',
    difficulty: 'Medium',
    expectedOutput: 'mango',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let fruits = ["mango", "kiwi", "pear"];', hasBug: false },
      {
        id: 2,
        code: 'let first = fruits[1];',
        hasBug: true,
        bugType: 'Wrong index',
        correctCode: 'let first = fruits[0];',
        hint: 'Index 0 is the first item.',
      },
      { id: 3, code: 'console.log(first);', hasBug: false },
    ],
  },
  {
    id: 10,
    title: 'Push Not Add',
    story: '🐸 Add a frog to the pond array!',
    concept: 'Arrays use push() to append',
    difficulty: 'Medium',
    expectedOutput: '["pad", "frog"]',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let pond = ["pad"];', hasBug: false },
      {
        id: 2,
        code: 'pond.add("frog");',
        hasBug: true,
        bugType: 'Wrong method',
        correctCode: 'pond.push("frog");',
        hint: 'The method is push, not add.',
      },
      { id: 3, code: 'console.log(pond);', hasBug: false },
    ],
  },
  {
    id: 11,
    title: 'Countdown Disaster',
    story: '😵 The loop runs forever!',
    concept: 'Loop counters must move toward the end',
    difficulty: 'Medium',
    expectedOutput: '0 1 2',
    bugCount: 1,
    lines: [
      {
        id: 1,
        code: 'for (let i = 0; i < 3; i--) {',
        hasBug: true,
        bugType: 'Wrong direction',
        correctCode: 'for (let i = 0; i < 3; i++) {',
        hint: 'Use i++ so i grows toward 3.',
      },
      { id: 2, code: '  console.log(i);', hasBug: false },
      { id: 3, code: '}', hasBug: false },
    ],
  },
  {
    id: 12,
    title: 'Off-By-One',
    story: '🔢 Count 1 through 4 inclusive!',
    concept: 'Use <= when you need the last number',
    difficulty: 'Medium',
    expectedOutput: '1 2 3 4',
    bugCount: 1,
    lines: [
      {
        id: 1,
        code: 'for (let i = 1; i < 4; i++) {',
        hasBug: true,
        bugType: 'Boundary too tight',
        correctCode: 'for (let i = 1; i <= 4; i++) {',
        hint: 'i <= 4 includes 4.',
      },
      { id: 2, code: '  console.log(i);', hasBug: false },
      { id: 3, code: '}', hasBug: false },
    ],
  },
  {
    id: 13,
    title: 'Length Trap',
    story: '📏 How many items? length is a property!',
    concept: 'Array length has no parentheses',
    difficulty: 'Medium',
    expectedOutput: '3',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let team = ["A", "B", "C"];', hasBug: false },
      {
        id: 2,
        code: 'console.log(team.length());',
        hasBug: true,
        bugType: 'length is not a function',
        correctCode: 'console.log(team.length);',
        hint: 'Drop the ().',
      },
    ],
  },
  {
    id: 14,
    title: 'Last Index',
    story: '🎯 Get the LAST gem in the chest!',
    concept: 'Last index is length - 1',
    difficulty: 'Medium',
    expectedOutput: 'ruby',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let gems = ["opal", "jade", "ruby"];', hasBug: false },
      {
        id: 2,
        code: 'let last = gems[gems.length];',
        hasBug: true,
        bugType: 'Index out of range',
        correctCode: 'let last = gems[gems.length - 1];',
        hint: 'Subtract 1 from length.',
      },
      { id: 3, code: 'console.log(last);', hasBug: false },
    ],
  },
  {
    id: 15,
    title: 'Join Mix-up',
    story: '🧵 Turn the array into one string!',
    concept: 'join() builds a string from array items',
    difficulty: 'Medium',
    expectedOutput: 'a-b-c',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let parts = ["a", "b", "c"];', hasBug: false },
      {
        id: 2,
        code: 'console.log(parts.split("-"));',
        hasBug: true,
        bugType: 'Wrong method',
        correctCode: 'console.log(parts.join("-"));',
        hint: 'Arrays use join; strings use split.',
      },
    ],
  },
  {
    id: 16,
    title: 'Double Find',
    story: '🎪 Two bugs — semicolon and index!',
    concept: 'Hunt every bug before you fix',
    difficulty: 'Medium',
    expectedOutput: 'Sum: 9',
    bugCount: 2,
    lines: [
      { id: 1, code: 'let nums = [2, 3, 4];', hasBug: false },
      {
        id: 2,
        code: 'let sum = 0',
        hasBug: true,
        bugType: 'Missing semicolon',
        correctCode: 'let sum = 0;',
        hint: 'Add ; after 0.',
      },
      {
        id: 3,
        code: 'for (let i = 0; i <= 3; i++) {',
        hasBug: true,
        bugType: 'Off-by-one on array',
        correctCode: 'for (let i = 0; i < 3; i++) {',
        hint: 'Valid indexes are 0, 1, 2 — use i < 3.',
      },
      { id: 4, code: '  sum += nums[i];', hasBug: false },
      { id: 5, code: '}', hasBug: false },
      { id: 6, code: 'console.log("Sum: " + sum);', hasBug: false },
    ],
  },
  // ——— HARD (17–24) ———
  {
    id: 17,
    title: 'Equals Trap',
    story: '🎯 Check if score is 100 — don\'t assign!',
    concept: '=== compares; = assigns',
    difficulty: 'Hard',
    expectedOutput: 'Winner!',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let score = 100;', hasBug: false },
      {
        id: 2,
        code: 'if (score = 100) {',
        hasBug: true,
        bugType: 'Assignment in condition',
        correctCode: 'if (score === 100) {',
        hint: 'Use === for comparison.',
      },
      { id: 3, code: '  console.log("Winner!");', hasBug: false },
      { id: 4, code: '}', hasBug: false },
    ],
  },
  {
    id: 18,
    title: 'Hot Or Not',
    story: '🌡️ Fan should turn on when it\'s hot!',
    concept: 'Pick the right comparison operator',
    difficulty: 'Hard',
    expectedOutput: 'Fan on',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let temp = 90;', hasBug: false },
      {
        id: 2,
        code: 'if (temp < 85) {',
        hasBug: true,
        bugType: 'Wrong comparison',
        correctCode: 'if (temp > 85) {',
        hint: 'Hot means greater than 85.',
      },
      { id: 3, code: '  console.log("Fan on");', hasBug: false },
      { id: 4, code: '}', hasBug: false },
    ],
  },
  {
    id: 19,
    title: 'And Vs Or',
    story: '🎫 Need BOTH ticket AND age!',
    concept: '&& means both conditions must be true',
    difficulty: 'Hard',
    expectedOutput: 'Enter',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let hasTicket = true;', hasBug: false },
      { id: 2, code: 'let age = 12;', hasBug: false },
      {
        id: 3,
        code: 'if (hasTicket || age >= 10) {',
        hasBug: true,
        bugType: 'Wrong logical operator',
        correctCode: 'if (hasTicket && age >= 10) {',
        hint: 'Use && so both must pass.',
      },
      { id: 4, code: '  console.log("Enter");', hasBug: false },
      { id: 5, code: '}', hasBug: false },
    ],
  },
  {
    id: 20,
    title: 'Else Missing',
    story: '🌓 Night path never runs!',
    concept: 'else handles the other branch',
    difficulty: 'Hard',
    expectedOutput: 'Night mode',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let day = false;', hasBug: false },
      { id: 2, code: 'if (day) {', hasBug: false },
      { id: 3, code: '  console.log("Day mode");', hasBug: false },
      {
        id: 4,
        code: '} if (!day) {',
        hasBug: true,
        bugType: 'Should use else',
        correctCode: '} else {',
        hint: 'Replace the second if with else.',
      },
      { id: 5, code: '  console.log("Night mode");', hasBug: false },
      { id: 6, code: '}', hasBug: false },
    ],
  },
  {
    id: 21,
    title: 'Type Check',
    story: '🧪 Is it a number? Use typeof!',
    concept: 'typeof returns a string like "number"',
    difficulty: 'Hard',
    expectedOutput: 'number',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let x = 7;', hasBug: false },
      {
        id: 2,
        code: 'console.log(typeof(x) == Number);',
        hasBug: true,
        bugType: 'Wrong typeof check',
        correctCode: 'console.log(typeof x);',
        hint: 'Just log typeof x (result is the string "number").',
      },
    ],
  },
  {
    id: 22,
    title: 'Template Trouble',
    story: '✨ Build a greeting with ${name}!',
    concept: 'Template literals use backticks `',
    difficulty: 'Hard',
    expectedOutput: 'Hello, Sam',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let name = "Sam";', hasBug: false },
      {
        id: 2,
        code: 'console.log("Hello, ${name}");',
        hasBug: true,
        bugType: 'Wrong quote style for template',
        correctCode: 'console.log(`Hello, ${name}`);',
        hint: 'Use backticks ` around the template.',
      },
    ],
  },
  {
    id: 23,
    title: 'Not Equal',
    story: '🚫 Skip if the password is wrong!',
    concept: '!== means not equal',
    difficulty: 'Hard',
    expectedOutput: 'Access denied',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let pass = "oops";', hasBug: false },
      {
        id: 2,
        code: 'if (pass === "secret") {',
        hasBug: true,
        bugType: 'Wrong condition direction',
        correctCode: 'if (pass !== "secret") {',
        hint: 'We want the message when pass is NOT secret.',
      },
      { id: 3, code: '  console.log("Access denied");', hasBug: false },
      { id: 4, code: '}', hasBug: false },
    ],
  },
  {
    id: 24,
    title: 'Twin Bugs',
    story: '🧨 Fix compare AND the loop bound!',
    concept: 'Multiple hard bugs in one snippet',
    difficulty: 'Hard',
    expectedOutput: 'OK',
    bugCount: 2,
    lines: [
      { id: 1, code: 'let n = 3;', hasBug: false },
      {
        id: 2,
        code: 'if (n = 3) {',
        hasBug: true,
        bugType: 'Assignment instead of compare',
        correctCode: 'if (n === 3) {',
        hint: 'Use ===.',
      },
      {
        id: 3,
        code: '  for (let i = 0; i <= 1; i++) {',
        hasBug: true,
        bugType: 'Loop runs twice; should once',
        correctCode: '  for (let i = 0; i < 1; i++) {',
        hint: 'i < 1 runs a single pass.',
      },
      { id: 4, code: '    console.log("OK");', hasBug: false },
      { id: 5, code: '  }', hasBug: false },
      { id: 6, code: '}', hasBug: false },
    ],
  },
  // ——— EXPERT (25–30) ———
  {
    id: 25,
    title: 'Silent Return',
    story: '🔧 Function computes but never sends it back!',
    concept: 'return passes the value out',
    difficulty: 'Expert',
    expectedOutput: '15',
    bugCount: 1,
    lines: [
      { id: 1, code: 'function triple(n) {', hasBug: false },
      { id: 2, code: '  let out = n * 3;', hasBug: false },
      {
        id: 3,
        code: '  out;',
        hasBug: true,
        bugType: 'Missing return',
        correctCode: '  return out;',
        hint: 'Write return before out.',
      },
      { id: 4, code: '}', hasBug: false },
      { id: 5, code: 'console.log(triple(5));', hasBug: false },
    ],
  },
  {
    id: 26,
    title: 'Param Swap',
    story: '📐 Add a and b — not a twice!',
    concept: 'Use every parameter',
    difficulty: 'Expert',
    expectedOutput: '12',
    bugCount: 1,
    lines: [
      { id: 1, code: 'function add(a, b) {', hasBug: false },
      {
        id: 2,
        code: '  return a + a;',
        hasBug: true,
        bugType: 'Wrong parameter',
        correctCode: '  return a + b;',
        hint: 'Second addend should be b.',
      },
      { id: 3, code: '}', hasBug: false },
      { id: 4, code: 'console.log(add(5, 7));', hasBug: false },
    ],
  },
  {
    id: 27,
    title: 'Base Case Blank',
    story: '🌀 Recursion needs a stop!',
    concept: 'Base case prevents infinite recursion',
    difficulty: 'Expert',
    expectedOutput: '6',
    bugCount: 1,
    lines: [
      { id: 1, code: 'function fact(n) {', hasBug: false },
      {
        id: 2,
        code: '  if (n === 0) { }',
        hasBug: true,
        bugType: 'Empty base case',
        correctCode: '  if (n === 0) { return 1; }',
        hint: 'Return 1 when n is 0.',
      },
      { id: 3, code: '  return n * fact(n - 1);', hasBug: false },
      { id: 4, code: '}', hasBug: false },
      { id: 5, code: 'console.log(fact(3));', hasBug: false },
    ],
  },
  {
    id: 28,
    title: 'Object Key',
    story: '🗝️ Read the score from the player object!',
    concept: 'Dot notation needs the exact key',
    difficulty: 'Expert',
    expectedOutput: '99',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let player = { score: 99 };', hasBug: false },
      {
        id: 2,
        code: 'console.log(player.Score);',
        hasBug: true,
        bugType: 'Wrong key casing',
        correctCode: 'console.log(player.score);',
        hint: 'Key is score with lowercase s.',
      },
    ],
  },
  {
    id: 29,
    title: 'Map Mistake',
    story: '🗺️ Double each number with map!',
    concept: 'map needs a return (or concise arrow)',
    difficulty: 'Expert',
    expectedOutput: '[2, 4, 6]',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let nums = [1, 2, 3];', hasBug: false },
      {
        id: 2,
        code: 'let doubled = nums.map(n => { n * 2; });',
        hasBug: true,
        bugType: 'Block body missing return',
        correctCode: 'let doubled = nums.map(n => n * 2);',
        hint: 'Use a concise arrow: n => n * 2',
      },
      { id: 3, code: 'console.log(doubled);', hasBug: false },
    ],
  },
  {
    id: 30,
    title: 'Final Squash',
    story: '🏆 Three bugs — the ultimate hunt!',
    concept: 'Combine syntax, loops, and returns',
    difficulty: 'Expert',
    expectedOutput: 'Sum: 6',
    bugCount: 3,
    lines: [
      { id: 1, code: 'function total(arr) {', hasBug: false },
      {
        id: 2,
        code: '  let s = 0',
        hasBug: true,
        bugType: 'Missing semicolon',
        correctCode: '  let s = 0;',
        hint: 'Add ; after 0.',
      },
      {
        id: 3,
        code: '  for (let i = 0; i <= arr.length; i++) {',
        hasBug: true,
        bugType: 'Off-by-one',
        correctCode: '  for (let i = 0; i < arr.length; i++) {',
        hint: 'Use i < arr.length.',
      },
      { id: 4, code: '    s += arr[i];', hasBug: false },
      { id: 5, code: '  }', hasBug: false },
      {
        id: 6,
        code: '  "Sum: " + s;',
        hasBug: true,
        bugType: 'Missing return',
        correctCode: '  return "Sum: " + s;',
        hint: 'Return the string.',
      },
      { id: 7, code: '}', hasBug: false },
      { id: 8, code: 'console.log(total([1, 2, 3]));', hasBug: false },
    ],
  },
];
