export interface CodeLine {
  id: number;
  code: string;
  hasBug: boolean;
  bugType?: string;
  correctCode?: string;
  hint?: string;
}

export interface BugHunter2Level {
  id: number;
  title: string;
  story: string;
  concept: string;
  difficulty: 'Easy' | 'Medium' | 'Hard' | 'Expert';
  lines: CodeLine[];
  expectedOutput: string;
  bugCount: number;
}

/** Bug Hunter 2 — 30 levels, easy → expert. Most snippets ≥5 lines so bugs hide in noise. */
export const bugHunter2Levels: BugHunter2Level[] = [
  // ——— EASY (1–8) ———
  {
    id: 1,
    title: 'Quote Quake',
    story: '🤖 The greeting string fell apart!',
    concept: 'Strings need matching quotes on both ends',
    difficulty: 'Easy',
    expectedOutput: 'Hi, coder!',
    bugCount: 1,
    lines: [
      { id: 1, code: '// Build a friendly greeting', hasBug: false },
      { id: 2, code: 'let ready = true;', hasBug: false },
      {
        id: 3,
        code: 'let msg = "Hi, coder!;',
        hasBug: true,
        bugType: 'Missing closing quote',
        correctCode: 'let msg = "Hi, coder!";',
        hint: 'Check whether this string is fully closed.',
      },
      { id: 4, code: 'let emoji = "👋";', hasBug: false },
      { id: 5, code: 'console.log(msg);', hasBug: false },
      { id: 6, code: '// Done', hasBug: false },
    ],
  },
  {
    id: 2,
    title: 'Semicolon Slip',
    story: '🎮 Score line is incomplete!',
    concept: 'End statements with a semicolon',
    difficulty: 'Easy',
    expectedOutput: 'Score: 50',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let player = "Sam";', hasBug: false },
      { id: 2, code: 'let level = 1;', hasBug: false },
      {
        id: 3,
        code: 'let score = 50',
        hasBug: true,
        bugType: 'Missing semicolon',
        correctCode: 'let score = 50;',
        hint: 'Something about how this statement ends looks unfinished.',
      },
      { id: 4, code: 'let bonus = 0;', hasBug: false },
      { id: 5, code: 'console.log("Score: " + score);', hasBug: false },
      { id: 6, code: 'console.log("Player: " + player);', hasBug: false },
    ],
  },
  {
    id: 3,
    title: 'Case Chaos',
    story: '🐱 The name variable got its case mixed up!',
    concept: 'Variable names are case-sensitive',
    difficulty: 'Easy',
    expectedOutput: 'Pixel',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let shelter = "Cosmic Cats";', hasBug: false },
      { id: 2, code: 'let petName = "Pixel";', hasBug: false },
      { id: 3, code: 'let age = 2;', hasBug: false },
      { id: 4, code: 'let fluffy = true;', hasBug: false },
      {
        id: 5,
        code: 'console.log(petname);',
        hasBug: true,
        bugType: 'Wrong casing',
        correctCode: 'console.log(petName);',
        hint: 'Names in JS care about letter size — look carefully.',
      },
      { id: 6, code: '// Print the pet name above', hasBug: false },
    ],
  },
  {
    id: 4,
    title: 'Forgotten Let',
    story: '🎂 Candles appeared from nowhere!',
    concept: 'Declare variables with let (or const)',
    difficulty: 'Easy',
    expectedOutput: '12',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let cake = "chocolate";', hasBug: false },
      { id: 2, code: 'let party = true;', hasBug: false },
      {
        id: 3,
        code: 'candles = 12;',
        hasBug: true,
        bugType: 'Undeclared variable',
        correctCode: 'let candles = 12;',
        hint: 'Was this variable properly introduced before it was used?',
      },
      { id: 4, code: 'let frosting = "vanilla";', hasBug: false },
      { id: 5, code: 'console.log(candles);', hasBug: false },
      { id: 6, code: '// Birthday setup complete', hasBug: false },
    ],
  },
  {
    id: 5,
    title: 'Paren Panic',
    story: '📢 console.log is missing a piece!',
    concept: 'Function calls need matching parentheses',
    difficulty: 'Easy',
    expectedOutput: 'Ready!',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let status = "booting";', hasBug: false },
      { id: 2, code: 'let engines = 2;', hasBug: false },
      { id: 3, code: 'status = "online";', hasBug: false },
      {
        id: 4,
        code: 'console.log("Ready!";',
        hasBug: true,
        bugType: 'Missing closing parenthesis',
        correctCode: 'console.log("Ready!");',
        hint: 'Count the opening and closing symbols on this call.',
      },
      { id: 5, code: 'let countdown = 3;', hasBug: false },
      { id: 6, code: '// Launch sequence', hasBug: false },
    ],
  },
  {
    id: 6,
    title: 'Plus Not Comma',
    story: '🧩 Glue text and a number together!',
    concept: 'Use + to concatenate strings and numbers',
    difficulty: 'Easy',
    expectedOutput: 'Level 3',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let world = "Forest";', hasBug: false },
      { id: 2, code: 'let n = 3;', hasBug: false },
      { id: 3, code: 'let lives = 5;', hasBug: false },
      {
        id: 4,
        code: 'console.log("Level " , n);',
        hasBug: true,
        bugType: 'Wrong join operator',
        correctCode: 'console.log("Level " + n);',
        hint: 'How do you glue text and a number into one message?',
      },
      { id: 5, code: 'let saved = false;', hasBug: false },
      { id: 6, code: '// Show the level number', hasBug: false },
    ],
  },
  {
    id: 7,
    title: 'Quote Mismatch',
    story: '📝 Opening " but closing with something else!',
    concept: 'Opening and closing quotes must match',
    difficulty: 'Easy',
    expectedOutput: 'Go!',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let race = "sprint";', hasBug: false },
      { id: 2, code: 'let lane = 4;', hasBug: false },
      {
        id: 3,
        code: "let shout = \"Go!';",
        hasBug: true,
        bugType: 'Mismatched quotes',
        correctCode: 'let shout = "Go!";',
        hint: 'The quotes on this string do not match each other.',
      },
      { id: 4, code: 'let timer = 0;', hasBug: false },
      { id: 5, code: 'console.log(shout);', hasBug: false },
      { id: 6, code: 'lane = lane + 0;', hasBug: false },
    ],
  },
  {
    id: 8,
    title: 'Const Trap',
    story: '🔒 You tried to change a const!',
    concept: 'Use let if the value will change',
    difficulty: 'Easy',
    expectedOutput: '2',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let game = "Hopper";', hasBug: false },
      {
        id: 2,
        code: 'const lives = 1;',
        hasBug: true,
        bugType: 'const cannot be reassigned',
        correctCode: 'let lives = 1;',
        hint: 'This value changes later — is the right keyword used?',
      },
      { id: 3, code: 'let shield = false;', hasBug: false },
      { id: 4, code: 'lives = 2;', hasBug: false },
      { id: 5, code: 'console.log(lives);', hasBug: false },
      { id: 6, code: '// Extra life collected', hasBug: false },
    ],
  },
  // ——— MEDIUM (9–16) ———
  {
    id: 9,
    title: 'Zero Start',
    story: '🍎 Grab the first fruit — arrays start at 0!',
    concept: 'First array index is 0',
    difficulty: 'Medium',
    expectedOutput: 'mango',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let basket = "picnic";', hasBug: false },
      { id: 2, code: 'let fruits = ["mango", "kiwi", "pear"];', hasBug: false },
      { id: 3, code: 'let count = fruits.length;', hasBug: false },
      {
        id: 4,
        code: 'let first = fruits[1];',
        hasBug: true,
        bugType: 'Wrong index',
        correctCode: 'let first = fruits[0];',
        hint: 'Which slot holds the first item in an array?',
      },
      { id: 5, code: 'let ripe = true;', hasBug: false },
      { id: 6, code: 'console.log(first);', hasBug: false },
    ],
  },
  {
    id: 10,
    title: 'Push Not Add',
    story: '🐸 Add a frog to the pond array!',
    concept: 'Arrays use push() to append',
    difficulty: 'Medium',
    expectedOutput: '["pad", "frog"]',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let weather = "sunny";', hasBug: false },
      { id: 2, code: 'let pond = ["pad"];', hasBug: false },
      { id: 3, code: 'let ripples = 3;', hasBug: false },
      {
        id: 4,
        code: 'pond.add("frog");',
        hasBug: true,
        bugType: 'Wrong method',
        correctCode: 'pond.push("frog");',
        hint: 'Arrays have a standard way to append — is this the right name?',
      },
      { id: 5, code: 'let deep = false;', hasBug: false },
      { id: 6, code: 'console.log(pond);', hasBug: false },
    ],
  },
  {
    id: 11,
    title: 'Countdown Disaster',
    story: '😵 The loop runs forever!',
    concept: 'Loop counters must move toward the end',
    difficulty: 'Medium',
    expectedOutput: '0 1 2',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let label = "count";', hasBug: false },
      { id: 2, code: 'let max = 3;', hasBug: false },
      {
        id: 3,
        code: 'for (let i = 0; i < 3; i--) {',
        hasBug: true,
        bugType: 'Wrong direction',
        correctCode: 'for (let i = 0; i < 3; i++) {',
        hint: 'Is the loop counter moving in a useful direction?',
      },
      { id: 4, code: '  console.log(i);', hasBug: false },
      { id: 5, code: '}', hasBug: false },
      { id: 6, code: 'let done = true;', hasBug: false },
    ],
  },
  {
    id: 12,
    title: 'Off-By-One',
    story: '🔢 Count 1 through 4 inclusive!',
    concept: 'Use <= when you need the last number',
    difficulty: 'Medium',
    expectedOutput: '1 2 3 4',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let start = 1;', hasBug: false },
      { id: 2, code: 'let end = 4;', hasBug: false },
      {
        id: 3,
        code: 'for (let i = 1; i < 4; i++) {',
        hasBug: true,
        bugType: 'Boundary too tight',
        correctCode: 'for (let i = 1; i <= 4; i++) {',
        hint: 'Does the loop stop before the last number you want?',
      },
      { id: 4, code: '  console.log(i);', hasBug: false },
      { id: 5, code: '}', hasBug: false },
      { id: 6, code: '// Inclusive range wanted', hasBug: false },
    ],
  },
  {
    id: 13,
    title: 'Length Trap',
    story: '📏 How many items? length is a property!',
    concept: 'Array length has no parentheses',
    difficulty: 'Medium',
    expectedOutput: '3',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let coach = "Kim";', hasBug: false },
      { id: 2, code: 'let team = ["A", "B", "C"];', hasBug: false },
      { id: 3, code: 'let ready = true;', hasBug: false },
      {
        id: 4,
        code: 'console.log(team.length());',
        hasBug: true,
        bugType: 'length is not a function',
        correctCode: 'console.log(team.length);',
        hint: 'Is length something you call, or something you read?',
      },
      { id: 5, code: 'let bench = [];', hasBug: false },
      { id: 6, code: '// Roster size', hasBug: false },
    ],
  },
  {
    id: 14,
    title: 'Last Index',
    story: '🎯 Get the LAST gem in the chest!',
    concept: 'Last index is length - 1',
    difficulty: 'Medium',
    expectedOutput: 'ruby',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let chest = "oak";', hasBug: false },
      { id: 2, code: 'let gems = ["opal", "jade", "ruby"];', hasBug: false },
      { id: 3, code: 'let locked = false;', hasBug: false },
      {
        id: 4,
        code: 'let last = gems[gems.length];',
        hasBug: true,
        bugType: 'Index out of range',
        correctCode: 'let last = gems[gems.length - 1];',
        hint: 'The last item is not quite at length itself…',
      },
      { id: 5, code: 'let sparkle = true;', hasBug: false },
      { id: 6, code: 'console.log(last);', hasBug: false },
    ],
  },
  {
    id: 15,
    title: 'Join Mix-up',
    story: '🧵 Turn the array into one string!',
    concept: 'join() builds a string from array items',
    difficulty: 'Medium',
    expectedOutput: 'a-b-c',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let label = "code";', hasBug: false },
      { id: 2, code: 'let parts = ["a", "b", "c"];', hasBug: false },
      { id: 3, code: 'let sep = "-";', hasBug: false },
      {
        id: 4,
        code: 'console.log(parts.split("-"));',
        hasBug: true,
        bugType: 'Wrong method',
        correctCode: 'console.log(parts.join("-"));',
        hint: 'Wrong tool for this job — arrays and strings use different methods here.',
      },
      { id: 5, code: 'let tagged = true;', hasBug: false },
      { id: 6, code: '// Flatten the parts', hasBug: false },
    ],
  },
  {
    id: 16,
    title: 'Double Find',
    story: '🎪 Two bugs — semicolon and index!',
    concept: 'Hunt every bug before you fix',
    difficulty: 'Medium',
    expectedOutput: 'Sum: 9',
    bugCount: 2,
    lines: [
      { id: 1, code: 'let title = "adder";', hasBug: false },
      { id: 2, code: 'let nums = [2, 3, 4];', hasBug: false },
      {
        id: 3,
        code: 'let sum = 0',
        hasBug: true,
        bugType: 'Missing semicolon',
        correctCode: 'let sum = 0;',
        hint: 'One statement here is missing its usual ending.',
      },
      {
        id: 4,
        code: 'for (let i = 0; i <= 3; i++) {',
        hasBug: true,
        bugType: 'Off-by-one on array',
        correctCode: 'for (let i = 0; i < 3; i++) {',
        hint: 'Will this loop ever visit an index that does not exist?',
      },
      { id: 5, code: '  sum += nums[i];', hasBug: false },
      { id: 6, code: '}', hasBug: false },
      { id: 7, code: 'console.log("Sum: " + sum);', hasBug: false },
    ],
  },
  // ——— HARD (17–24) ———
  {
    id: 17,
    title: 'Equals Trap',
    story: '🎯 Check if score is 100 — don\'t assign!',
    concept: '=== compares; = assigns',
    difficulty: 'Hard',
    expectedOutput: 'Winner!',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let round = 5;', hasBug: false },
      { id: 2, code: 'let score = 100;', hasBug: false },
      { id: 3, code: 'let target = 100;', hasBug: false },
      {
        id: 4,
        code: 'if (score = 100) {',
        hasBug: true,
        bugType: 'Assignment in condition',
        correctCode: 'if (score === 100) {',
        hint: 'Are you comparing, or accidentally changing the value?',
      },
      { id: 5, code: '  console.log("Winner!");', hasBug: false },
      { id: 6, code: '}', hasBug: false },
      { id: 7, code: 'let cheer = true;', hasBug: false },
    ],
  },
  {
    id: 18,
    title: 'Hot Or Not',
    story: '🌡️ Fan should turn on when it\'s hot!',
    concept: 'Pick the right comparison operator',
    difficulty: 'Hard',
    expectedOutput: 'Fan on',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let room = "lab";', hasBug: false },
      { id: 2, code: 'let temp = 90;', hasBug: false },
      { id: 3, code: 'let limit = 85;', hasBug: false },
      {
        id: 4,
        code: 'if (temp < 85) {',
        hasBug: true,
        bugType: 'Wrong comparison',
        correctCode: 'if (temp > 85) {',
        hint: 'Read the story again — when should the fan turn on?',
      },
      { id: 5, code: '  console.log("Fan on");', hasBug: false },
      { id: 6, code: '}', hasBug: false },
      { id: 7, code: 'let humidity = 40;', hasBug: false },
    ],
  },
  {
    id: 19,
    title: 'And Vs Or',
    story: '🎫 Need BOTH ticket AND age!',
    concept: '&& means both conditions must be true',
    difficulty: 'Hard',
    expectedOutput: 'Enter',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let gate = "north";', hasBug: false },
      { id: 2, code: 'let hasTicket = true;', hasBug: false },
      { id: 3, code: 'let age = 12;', hasBug: false },
      {
        id: 4,
        code: 'if (hasTicket || age >= 10) {',
        hasBug: true,
        bugType: 'Wrong logical operator',
        correctCode: 'if (hasTicket && age >= 10) {',
        hint: 'Do you need one condition, or both at once?',
      },
      { id: 5, code: '  console.log("Enter");', hasBug: false },
      { id: 6, code: '}', hasBug: false },
      { id: 7, code: 'let stamp = "ok";', hasBug: false },
    ],
  },
  {
    id: 20,
    title: 'Else Missing',
    story: '🌓 Night path never runs!',
    concept: 'else handles the other branch',
    difficulty: 'Hard',
    expectedOutput: 'Night mode',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let theme = "auto";', hasBug: false },
      { id: 2, code: 'let day = false;', hasBug: false },
      { id: 3, code: 'if (day) {', hasBug: false },
      { id: 4, code: '  console.log("Day mode");', hasBug: false },
      {
        id: 5,
        code: '} if (!day) {',
        hasBug: true,
        bugType: 'Should use else',
        correctCode: '} else {',
        hint: 'There is a cleaner way to handle the other branch.',
      },
      { id: 6, code: '  console.log("Night mode");', hasBug: false },
      { id: 7, code: '}', hasBug: false },
    ],
  },
  {
    id: 21,
    title: 'Type Check',
    story: '🧪 Is it a number? Use typeof!',
    concept: 'typeof returns a string like "number"',
    difficulty: 'Hard',
    expectedOutput: 'number',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let label = "probe";', hasBug: false },
      { id: 2, code: 'let x = 7;', hasBug: false },
      { id: 3, code: 'let checked = false;', hasBug: false },
      {
        id: 4,
        code: 'console.log(typeof(x) == Number);',
        hasBug: true,
        bugType: 'Wrong typeof check',
        correctCode: 'console.log(typeof x);',
        hint: 'typeof already answers the question — simplify what you print.',
      },
      { id: 5, code: 'checked = true;', hasBug: false },
      { id: 6, code: '// Type report', hasBug: false },
    ],
  },
  {
    id: 22,
    title: 'Template Trouble',
    story: '✨ Build a greeting with ${name}!',
    concept: 'Template literals use backticks `',
    difficulty: 'Hard',
    expectedOutput: 'Hello, Sam',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let locale = "en";', hasBug: false },
      { id: 2, code: 'let name = "Sam";', hasBug: false },
      { id: 3, code: 'let polite = true;', hasBug: false },
      {
        id: 4,
        code: 'console.log("Hello, ${name}");',
        hasBug: true,
        bugType: 'Wrong quote style for template',
        correctCode: 'console.log(`Hello, ${name}`);',
        hint: '${...} only works inside a special kind of string.',
      },
      { id: 5, code: 'let wave = true;', hasBug: false },
      { id: 6, code: '// Personalized hello', hasBug: false },
    ],
  },
  {
    id: 23,
    title: 'Not Equal',
    story: '🚫 Skip if the password is wrong!',
    concept: '!== means not equal',
    difficulty: 'Hard',
    expectedOutput: 'Access denied',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let user = "guest";', hasBug: false },
      { id: 2, code: 'let pass = "oops";', hasBug: false },
      { id: 3, code: 'let attempts = 1;', hasBug: false },
      {
        id: 4,
        code: 'if (pass === "secret") {',
        hasBug: true,
        bugType: 'Wrong condition direction',
        correctCode: 'if (pass !== "secret") {',
        hint: 'Should this message appear when the password matches, or when it fails?',
      },
      { id: 5, code: '  console.log("Access denied");', hasBug: false },
      { id: 6, code: '}', hasBug: false },
      { id: 7, code: 'let locked = true;', hasBug: false },
    ],
  },
  {
    id: 24,
    title: 'Twin Bugs',
    story: '🧨 Fix compare AND the loop bound!',
    concept: 'Multiple hard bugs in one snippet',
    difficulty: 'Hard',
    expectedOutput: 'OK',
    bugCount: 2,
    lines: [
      { id: 1, code: 'let mode = "strict";', hasBug: false },
      { id: 2, code: 'let n = 3;', hasBug: false },
      {
        id: 3,
        code: 'if (n = 3) {',
        hasBug: true,
        bugType: 'Assignment instead of compare',
        correctCode: 'if (n === 3) {',
        hint: 'Same trap as before — compare carefully.',
      },
      {
        id: 4,
        code: '  for (let i = 0; i <= 1; i++) {',
        hasBug: true,
        bugType: 'Loop runs twice; should once',
        correctCode: '  for (let i = 0; i < 1; i++) {',
        hint: 'How many times should the inner loop actually run?',
      },
      { id: 5, code: '    console.log("OK");', hasBug: false },
      { id: 6, code: '  }', hasBug: false },
      { id: 7, code: '}', hasBug: false },
    ],
  },
  // ——— EXPERT (25–30) ———
  {
    id: 25,
    title: 'Silent Return',
    story: '🔧 Function computes but never sends it back!',
    concept: 'return passes the value out',
    difficulty: 'Expert',
    expectedOutput: '15',
    bugCount: 1,
    lines: [
      { id: 1, code: '// Triple helper', hasBug: false },
      { id: 2, code: 'function triple(n) {', hasBug: false },
      { id: 3, code: '  let out = n * 3;', hasBug: false },
      {
        id: 4,
        code: '  out;',
        hasBug: true,
        bugType: 'Missing return',
        correctCode: '  return out;',
        hint: 'Computing a value is not the same as sending it back.',
      },
      { id: 5, code: '}', hasBug: false },
      { id: 6, code: 'let sample = 5;', hasBug: false },
      { id: 7, code: 'console.log(triple(5));', hasBug: false },
    ],
  },
  {
    id: 26,
    title: 'Param Swap',
    story: '📐 Add a and b — not a twice!',
    concept: 'Use every parameter',
    difficulty: 'Expert',
    expectedOutput: '12',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let unit = "sum";', hasBug: false },
      { id: 2, code: 'function add(a, b) {', hasBug: false },
      {
        id: 3,
        code: '  return a + a;',
        hasBug: true,
        bugType: 'Wrong parameter',
        correctCode: '  return a + b;',
        hint: 'Are both parameters being used?',
      },
      { id: 4, code: '}', hasBug: false },
      { id: 5, code: 'let left = 5;', hasBug: false },
      { id: 6, code: 'let right = 7;', hasBug: false },
      { id: 7, code: 'console.log(add(5, 7));', hasBug: false },
    ],
  },
  {
    id: 27,
    title: 'Base Case Blank',
    story: '🌀 Recursion needs a stop!',
    concept: 'Base case prevents infinite recursion',
    difficulty: 'Expert',
    expectedOutput: '6',
    bugCount: 1,
    lines: [
      { id: 1, code: '// Factorial', hasBug: false },
      { id: 2, code: 'function fact(n) {', hasBug: false },
      {
        id: 3,
        code: '  if (n === 0) { }',
        hasBug: true,
        bugType: 'Empty base case',
        correctCode: '  if (n === 0) { return 1; }',
        hint: 'Recursion needs a clear stop — this base case looks empty.',
      },
      { id: 4, code: '  return n * fact(n - 1);', hasBug: false },
      { id: 5, code: '}', hasBug: false },
      { id: 6, code: 'let n = 3;', hasBug: false },
      { id: 7, code: 'console.log(fact(3));', hasBug: false },
    ],
  },
  {
    id: 28,
    title: 'Object Key',
    story: '🗝️ Read the score from the player object!',
    concept: 'Dot notation needs the exact key',
    difficulty: 'Expert',
    expectedOutput: '99',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let game = "Arena";', hasBug: false },
      { id: 2, code: 'let player = { score: 99 };', hasBug: false },
      { id: 3, code: 'let lives = 3;', hasBug: false },
      {
        id: 4,
        code: 'console.log(player.Score);',
        hasBug: true,
        bugType: 'Wrong key casing',
        correctCode: 'console.log(player.score);',
        hint: 'Object keys care about exact spelling and letter size.',
      },
      { id: 5, code: 'let rank = "A";', hasBug: false },
      { id: 6, code: '// HUD score readout', hasBug: false },
    ],
  },
  {
    id: 29,
    title: 'Map Mistake',
    story: '🗺️ Double each number with map!',
    concept: 'map needs a return (or concise arrow)',
    difficulty: 'Expert',
    expectedOutput: '[2, 4, 6]',
    bugCount: 1,
    lines: [
      { id: 1, code: 'let tag = "doubler";', hasBug: false },
      { id: 2, code: 'let nums = [1, 2, 3];', hasBug: false },
      { id: 3, code: 'let scale = 2;', hasBug: false },
      {
        id: 4,
        code: 'let doubled = nums.map(n => { n * 2; });',
        hasBug: true,
        bugType: 'Block body missing return',
        correctCode: 'let doubled = nums.map(n => n * 2);',
        hint: 'With curly braces, map needs an explicit result — or a shorter arrow form.',
      },
      { id: 5, code: 'let ready = true;', hasBug: false },
      { id: 6, code: 'console.log(doubled);', hasBug: false },
    ],
  },
  {
    id: 30,
    title: 'Final Squash',
    story: '🏆 Three bugs — the ultimate hunt!',
    concept: 'Combine syntax, loops, and returns',
    difficulty: 'Expert',
    expectedOutput: 'Sum: 6',
    bugCount: 3,
    lines: [
      { id: 1, code: '// Sum helper for arrays', hasBug: false },
      { id: 2, code: 'function total(arr) {', hasBug: false },
      {
        id: 3,
        code: '  let s = 0',
        hasBug: true,
        bugType: 'Missing semicolon',
        correctCode: '  let s = 0;',
        hint: 'One statement here is missing its usual ending.',
      },
      {
        id: 4,
        code: '  for (let i = 0; i <= arr.length; i++) {',
        hasBug: true,
        bugType: 'Off-by-one',
        correctCode: '  for (let i = 0; i < arr.length; i++) {',
        hint: 'Does the loop stop before walking off the end of the array?',
      },
      { id: 5, code: '    s += arr[i];', hasBug: false },
      { id: 6, code: '  }', hasBug: false },
      {
        id: 7,
        code: '  "Sum: " + s;',
        hasBug: true,
        bugType: 'Missing return',
        correctCode: '  return "Sum: " + s;',
        hint: 'The function builds a message but never hands it back.',
      },
      { id: 8, code: '}', hasBug: false },
      { id: 9, code: 'let data = [1, 2, 3];', hasBug: false },
      { id: 10, code: 'console.log(total([1, 2, 3]));', hasBug: false },
    ],
  },
];
