import type { ObjectLevel } from './objectLockerLevels';

/**
 * Method chapter — levels 19+ after Final Character Game.
 * 19–28 basics, then hero methods + plays, then enemy + finale.
 */
export const objectLockerMethodLevels: ObjectLevel[] = [
  // ——— METHOD BASICS (10) ———
  {
    id: 19,
    title: 'Method Intro',
    concept: 'A method is an action stored on an object — call it with ()',
    instruction: 'Call the hop method on frog. Type frog.hop() with empty parentheses.',
    hint: 'Object, then a dot, then the method name, then ().',
    explanation: 'frog.hop() means: run the hop action that lives on the frog object.',
    mode: 'method',
    chapter: 'methods',
    startObject: { name: 'Pip' },
    methodNames: ['hop'],
    starterCode: '',
    solutions: ['frog.hop()', 'frog.hop( )'],
  },
  {
    id: 20,
    title: 'Empty Parentheses',
    concept: 'Even with no inputs, methods need ()',
    instruction: 'Ring the bell — call bell.ring() (empty parentheses required).',
    hint: 'bell.ring without () is just a property name — add ().',
    explanation: '() tells JavaScript “run this action now.”',
    mode: 'method',
    chapter: 'methods',
    startObject: { loud: true },
    methodNames: ['ring'],
    starterCode: '',
    solutions: ['bell.ring()', 'bell.ring( )'],
  },
  {
    id: 21,
    title: 'Property vs Method',
    concept: 'Properties hold values; methods do work',
    instruction: 'Read the cat\'s name with a property (no parentheses): cat.name',
    hint: 'Properties skip (). Methods use ().',
    explanation: 'cat.name peeks a value. cat.meow() would run an action.',
    mode: 'access',
    chapter: 'methods',
    startObject: { name: 'Miso', age: 2 },
    expectedValue: 'Miso',
    starterCode: '',
    solutions: ['cat.name'],
  },
  {
    id: 22,
    title: 'Call the Action',
    concept: 'Same object — now run its method',
    instruction: 'Make the cat meow: call cat.meow()',
    hint: 'Method name + ().',
    explanation: 'One object can have both data (name) and actions (meow).',
    mode: 'method',
    chapter: 'methods',
    startObject: { name: 'Miso' },
    methodNames: ['meow'],
    starterCode: '',
    solutions: ['cat.meow()', 'cat.meow( )'],
  },
  {
    id: 23,
    title: 'Method Arguments',
    concept: 'Put values inside the parentheses',
    instruction: 'Call greeter.say with the string "hi" inside the parentheses.',
    hint: 'greeter.say("hi") — quotes around hi.',
    explanation: 'Arguments are inputs you hand to a method when you call it.',
    mode: 'method',
    chapter: 'methods',
    startObject: { mood: 'friendly' },
    methodNames: ['say'],
    starterCode: '',
    solutions: ['greeter.say("hi")', "greeter.say('hi')"],
  },
  {
    id: 24,
    title: 'Assign a Method',
    concept: 'You can attach a new method with = function() {}',
    instruction: 'Add an empty beep method to robot: robot.beep = function() {}',
    hint: 'Right side is function() {} — empty braces for now.',
    explanation: 'Methods are functions stored in object keys — just like values, but callable.',
    mode: 'method',
    chapter: 'methods',
    startObject: { name: 'Beep' },
    methodNames: ['beep'],
    starterCode: '',
    solutions: [
      'robot.beep = function() {}',
      'robot.beep = function(){}',
      'robot.beep = function () {}',
      'robot.beep = () => {}',
      'robot.beep = ()=>{}',
    ],
  },
  {
    id: 25,
    title: 'Call What You Added',
    concept: 'After assigning, call the method',
    instruction: 'Call the beep method: robot.beep()',
    hint: 'Same call pattern as before.',
    explanation: 'Assign stores the action; () runs it.',
    mode: 'method',
    chapter: 'methods',
    startObject: { name: 'Beep' },
    methodNames: ['beep'],
    starterCode: '',
    solutions: ['robot.beep()', 'robot.beep( )'],
  },
  {
    id: 26,
    title: 'Method in a Literal',
    concept: 'Objects can include methods when you create them',
    instruction: 'Create bird with a fly method: let bird = { fly: function() {} }',
    hint: 'Inside braces: fly key, colon, then function() {}',
    explanation: 'fly is a key whose value is a function — a method baked into the object.',
    mode: 'method',
    chapter: 'methods',
    startObject: {},
    methodNames: ['fly'],
    starterCode: '',
    solutions: [
      'let bird = { fly: function() {} }',
      'let bird = {fly: function() {}}',
      'let bird = { fly: function(){} }',
      'let bird = { fly: () => {} }',
      'let bird = { fly() {} }',
      'let bird = {fly(){}}',
    ],
  },
  {
    id: 27,
    title: 'Take Flight',
    concept: 'Call a method from an object you built',
    instruction: 'Call bird.fly()',
    hint: 'bird, then .fly, then ().',
    explanation: 'Creating + calling methods is how game characters gain abilities.',
    mode: 'method',
    chapter: 'methods',
    startObject: {},
    methodNames: ['fly'],
    starterCode: '',
    solutions: ['bird.fly()', 'bird.fly( )'],
  },
  {
    id: 28,
    title: 'Methods Pack',
    concept: 'One object can hold many methods',
    instruction: 'Call player.jump() — practice one more clean method call.',
    hint: 'player.jump()',
    explanation: 'Games hang lots of actions on one character object: jump, shoot, grow…',
    mode: 'method',
    chapter: 'methods',
    startObject: { name: 'Hero' },
    methodNames: ['jump'],
    starterCode: '',
    solutions: ['player.jump()', 'player.jump( )'],
  },

  // ——— HERO METHODS + PRACTICE ———
  {
    id: 29,
    title: 'Methods · Hero Shoot',
    concept: 'Give your hero a shoot method (no enemies yet)',
    instruction: 'Attach shoot to hero: hero.shoot = function() {}',
    hint: 'Same assign pattern: hero.shoot = function() {}',
    explanation: 'shoot is now an action key on your hero — you\'ll fire it in the arena next!',
    mode: 'method',
    chapter: 'methods',
    startObject: {},
    methodNames: ['shoot'],
    unlockMethod: 'shoot',
    starterCode: '',
    solutions: [
      'hero.shoot = function() {}',
      'hero.shoot = function(){}',
      'hero.shoot = function () {}',
      'hero.shoot = () => {}',
      'hero.shoot = ()=>{}',
    ],
  },
  {
    id: 30,
    title: 'Methods · Shoot Practice',
    concept: 'Use hero.shoot() — hit targets, no enemies',
    instruction: 'Move and press Shoot (or S). Hit 5 floating targets with your shoot method. No enemies here!',
    hint: 'Shoot fires a spark the direction you face. Line up with a target.',
    explanation: 'Calling hero.shoot() in a game loop is how shots leave your character.',
    mode: 'playMethods',
    chapter: 'methods',
    playKind: 'shootPractice',
    startObject: {},
    starterCode: '',
    solutions: [],
  },
  {
    id: 31,
    title: 'Methods · Super Jump',
    concept: 'Add a superJump method for huge hops',
    instruction: 'Attach superJump: hero.superJump = function() {}',
    hint: 'hero.superJump = function() {}',
    explanation: 'superJump is another method key — games pick which method to call for each button.',
    mode: 'method',
    chapter: 'methods',
    startObject: {},
    methodNames: ['superJump'],
    unlockMethod: 'superJump',
    starterCode: '',
    solutions: [
      'hero.superJump = function() {}',
      'hero.superJump = function(){}',
      'hero.superJump = function () {}',
      'hero.superJump = () => {}',
      'hero.superJump = ()=>{}',
    ],
  },
  {
    id: 32,
    title: 'Methods · Grow',
    concept: 'Add a grow method that powers up size',
    instruction: 'Attach grow: hero.grow = function() {}',
    hint: 'hero.grow = function() {}',
    explanation: 'grow can change how big your hero draws — still just a method on the object.',
    mode: 'method',
    chapter: 'methods',
    startObject: {},
    methodNames: ['grow'],
    unlockMethod: 'grow',
    starterCode: '',
    solutions: [
      'hero.grow = function() {}',
      'hero.grow = function(){}',
      'hero.grow = function () {}',
      'hero.grow = () => {}',
      'hero.grow = ()=>{}',
    ],
  },
  {
    id: 33,
    title: 'Methods · Hero Combo',
    concept: 'Practice shoot, superJump, and grow together — still no enemies',
    instruction: 'Use Shoot, Super Jump, and Grow. Collect 5 orbs (Grow helps reach them!). No enemies yet.',
    hint: 'Super Jump goes higher. Grow makes you bigger so orbs are easier to touch.',
    explanation: 'Your hero object now has data AND methods — that\'s a real game character.',
    mode: 'playMethods',
    chapter: 'methods',
    playKind: 'heroCombo',
    startObject: {},
    starterCode: '',
    solutions: [],
  },

  // ——— ENEMY ———
  {
    id: 34,
    title: 'Methods · Enemy Object',
    concept: 'Build an enemy the same way you built your hero',
    instruction:
      'Create enemy with: name (string), hp (number 3–20), and speed (number 1–10). Invent any foe!',
    hint: 'Example: let enemy = { name: "Glitch", hp: 8, speed: 4 }',
    explanation: 'Enemies are objects too — same key:value lockers as heroes.',
    mode: 'create',
    chapter: 'methods',
    startObject: {},
    starterCode: '',
    solutions: [],
    createVar: 'enemy',
    createFields: [
      { key: 'name', type: 'string' },
      { key: 'hp', type: 'number', min: 3, max: 20 },
      { key: 'speed', type: 'number', min: 1, max: 10 },
    ],
  },
  {
    id: 35,
    title: 'Methods · Enemy Actions',
    concept: 'Give the enemy methods of its own',
    instruction: 'Attach chase: enemy.chase = function() {}',
    hint: 'Same pattern as hero methods — enemy.chase = function() {}',
    explanation: 'Enemy AI is often just methods the game calls each frame (chase, roar, attack…).',
    mode: 'method',
    chapter: 'methods',
    startObject: {},
    methodNames: ['chase'],
    unlockMethod: 'enemyChase',
    starterCode: '',
    solutions: [
      'enemy.chase = function() {}',
      'enemy.chase = function(){}',
      'enemy.chase = function () {}',
      'enemy.chase = () => {}',
      'enemy.chase = ()=>{}',
    ],
  },
  {
    id: 36,
    title: 'Methods · Enemy Roar',
    concept: 'One more enemy method',
    instruction: 'Attach roar: enemy.roar = function() {}',
    hint: 'enemy.roar = function() {}',
    explanation: 'Multiple methods = a richer enemy. Next you\'ll face it in your city!',
    mode: 'method',
    chapter: 'methods',
    startObject: {},
    methodNames: ['roar'],
    unlockMethod: 'enemyRoar',
    starterCode: '',
    solutions: [
      'enemy.roar = function() {}',
      'enemy.roar = function(){}',
      'enemy.roar = function () {}',
      'enemy.roar = () => {}',
      'enemy.roar = ()=>{}',
    ],
  },
  {
    id: 37,
    title: 'Methods · Final Arena',
    concept: 'Hero methods vs enemy methods in your city',
    instruction:
      'Defeat the enemy! Shoot to damage it, Super Jump to dodge, Grow for bigger shots. Enemy uses chase. Drop its hp to 0.',
    hint: 'Keep distance, shoot when lined up. Grow boosts shot size. Super Jump to leap over the foe.',
    explanation: 'You designed objects AND methods — that\'s the core of character coding in games!',
    mode: 'playMethods',
    chapter: 'methods',
    playKind: 'arena',
    startObject: {},
    starterCode: '',
    solutions: [],
  },
];
